export const COMPONENT_EMPTY_RESULT = 'COMPONENT_EMPTY_RESULT'
export const COMPONENT_TITLE_EMPTY_RESULT = 'COMPONENT_TITLE_EMPTY_RESULT'
export const COMPONENT_SEARCH_BAR = 'COMPONENT_SEARCH_BAR'
export const COMPONENT_LOADING = 'COMPONENT_LOADING'
export const COMPONENT_PRODUCT_LIST = 'COMPONENT_PRODUCT_LIST'
export const COMPONENT_PRODUCT_CARD = 'COMPONENT_PRODUCT_CARD'
export const COMPONENT_PAGINATION = 'COMPONENT_PAGINATION'

